[versions]
kotlin = "1.9.10"
dokka = "1.9.0"

## SDK Versions
minSdk = "24"
targetSdk = "34"
compileSdk = "34"

# Dependencies
android-gradle-plugin = "8.2.0-beta06"
gradle-versions = "0.48.0"
detekt = "1.23.1"

accompanist = "0.32.0"
androidx-activity-compose = "1.8.0-rc01"
androidx-core = "1.12.0"
androidx-lifecycle = "2.6.2"
androidx-test-junit = "1.1.5"

compose = "1.5.1"
# https://androidx.dev/storage/compose-compiler/repository/
# https://developer.android.com/jetpack/androidx/releases/compose-compiler
composeCompiler = "1.5.3"

kotlinx-coroutines = "1.7.3"
kotlinx-collections-immutable = "0.3.5"

libphonenumber = "8.13.17"

junit = "4.13.2"
robolectric = "4.10.3"
paparazzi = "1.3.1"

[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-compose = {module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle"}
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-test-junit = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-junit" }

compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "composeCompiler" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

libphonenumber = { module = "io.michaelrocks:libphonenumber-android", version.ref = "libphonenumber" }

kotlinx-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }

junit = { module = "junit:junit", version.ref = "junit" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
roboelectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

[plugins]
gradleVersions = { id = "com.github.ben-manes.versions", version.ref = "gradle-versions" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
